npx shadcn@latest add button
npx shadcn@latest add card
npx shadcn@latest add input
npx shadcn@latest add label
npx shadcn@latest add tabs
npx shadcn@latest add switch
npx shadcn@latest add alert
npx shadcn@latest add select
npx shadcn@latest add progress
npx shadcn@latest add skeleton
npx shadcn@latest add scroll-area
npx shadcn@latest add separator
npx shadcn@latest add tooltip
npx shadcn@latest add hover-card
npx shadcn@latest add radio-group
npx shadcn@latest add command
npx shadcn@latest add popover
npx shadcn@latest add sheet
npx shadcn@latest add toggle-group
npx shadcn@latest add textarea
npx shadcn@latest add table
npx shadcn@latest add dropdown-menu
npx shadcn@latest add breadcrumb
npx shadcn@latest add slider
npx shadcn@latest add navigation-menu
npx shadcn@latest add toast

