name: Mobile App Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'temp-branch-*'
  pull_request:
    branches:
      - 'temp-branch-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Extract tenant ID
        id: tenant
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          # Extract tenant ID: capture the digits between 'temp-branch-' and the following hyphen
          TENANT_ID=$(echo "$BRANCH_NAME" | sed -E 's/^temp-branch-([0-9]+)-.*/\1/')
          echo "tenant_id=$TENANT_ID" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install @capacitor/core@7.2.0
          npm install --save-dev @capacitor/assets @capacitor/cli@7.2.0

      - name: Setup Android platform
        run: |
          if [ -d "android" ]; then
            echo "Removing existing Android platform..."
            rm -rf android
          fi
          echo "Adding Android platform..."
          npx cap add android

      - name: Run npx cap sync
        run: |
          npx cap sync android

      - name: Generate Assets
        run: |
          npx capacitor-assets generate --android

      - name: Grant execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Download Keystore from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          mkdir -p android/.secure
          aws s3 cp "s3://afobata/androidKey.jks" android/.secure/androidKey.jks --region ${{ secrets.AWS_REGION }}
          ls -la android/.secure/
          file android/.secure/androidKey.jks

      - name: Build Android (APK and AAB)
        run: |
          cd android
          KEYSTORE_PATH="$PWD/.secure/androidKey.jks"
          echo "Using keystore at: $KEYSTORE_PATH"

          if [[ "${{ github.event.inputs.debug_mode }}" == "true" ]]; then
            ./gradlew assembleDebug bundleDebug --parallel --max-workers=6 --configure-on-demand --daemon
          else
            ./gradlew assembleRelease bundleRelease --parallel --max-workers=6 --configure-on-demand --daemon \
              -Pandroid.injected.signing.store.file="$KEYSTORE_PATH" \
              -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
              -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
              -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
          fi

      - name: Generate build type
        id: build_info
        run: |
          echo "build_type=$(if [[ "${{ github.event.inputs.debug_mode }}" == "true" ]]; then echo "debug"; else echo "release"; fi)" >> $GITHUB_OUTPUT

      - name: Upload to S3
        id: s3_upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          BUILD_TYPE="${{ steps.build_info.outputs.build_type }}"
          TENANT_ID="${{ steps.tenant.outputs.tenant_id }}"
          BUILD_PATH="mobile-builds/android/${TENANT_ID}"

          NEW_APK_NAME="app-${TENANT_ID}.apk"
          NEW_AAB_NAME="app-${TENANT_ID}.aab"
          SOURCE_APK="android/app/build/outputs/apk/${BUILD_TYPE}/app-${BUILD_TYPE}.apk"
          SOURCE_AAB="android/app/build/outputs/bundle/${BUILD_TYPE}/app-${BUILD_TYPE}.aab"

          [ -f "$SOURCE_APK" ] && cp "$SOURCE_APK" "/tmp/$NEW_APK_NAME" || { echo "Error: APK file not found at $SOURCE_APK"; exit 1; }
          [ -f "$SOURCE_AAB" ] && cp "$SOURCE_AAB" "/tmp/$NEW_AAB_NAME" || { echo "Error: AAB file not found at $SOURCE_AAB"; exit 1; }

          S3_PATH_APK="s3://afobata/${BUILD_PATH}/${NEW_APK_NAME}"
          S3_PATH_AAB="s3://afobata/${BUILD_PATH}/${NEW_AAB_NAME}"

          aws s3 cp "/tmp/$NEW_APK_NAME" "$S3_PATH_APK" --region ${{ secrets.AWS_REGION }} & 
          aws s3 cp "/tmp/$NEW_AAB_NAME" "$S3_PATH_AAB" --region ${{ secrets.AWS_REGION }} & 
          wait

          echo "s3_url_apk=https://s3.${{ secrets.AWS_REGION }}.amazonaws.com/afobata/${BUILD_PATH}/${NEW_APK_NAME}" >> $GITHUB_OUTPUT
          echo "s3_url_aab=https://s3.${{ secrets.AWS_REGION }}.amazonaws.com/afobata/${BUILD_PATH}/${NEW_AAB_NAME}" >> $GITHUB_OUTPUT

          echo "{
            \"buildTime\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
            \"commit\":\"${{ github.sha }}\",
            \"branch\":\"${{ github.ref_name }}\",
            \"environment\":\"${{ github.event.inputs.environment }}\",
            \"buildType\":\"${BUILD_TYPE}\",
            \"tenantId\":\"${TENANT_ID}\",
            \"artifacts\": {
              \"apk\": \"${BUILD_PATH}/${NEW_APK_NAME}\",
              \"aab\": \"${BUILD_PATH}/${NEW_AAB_NAME}\"
            }
          }" > buildinfo.json

          aws s3 cp buildinfo.json "s3://afobata/${BUILD_PATH}/buildinfo.json" --region ${{ secrets.AWS_REGION }}

      - name: Send Build Notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-trust-code: ${{ secrets.NEXT_PUBLIC_TRUST_CODE }}" \
            -d "{
              \"tenantId\": \"${{ steps.tenant.outputs.tenant_id }}\",
              \"downloadUrls\": {
                \"apk\": \"${{ steps.s3_upload.outputs.s3_url_apk }}\",
                \"aab\": \"${{ steps.s3_upload.outputs.s3_url_aab }}\"
              },
              \"buildType\": \"${{ steps.build_info.outputs.build_type }}\",
              \"buildTime\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
              \"commit\":\"${{ github.sha }}\",
              \"branch\":\"${{ github.ref_name }}\"
            }" \
            https://afobata.com/api/a/post/callback

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ steps.tenant.outputs.tenant_id }}
          path: |
            android/app/build/outputs/apk/${{ steps.build_info.outputs.build_type }}/app-${{ steps.build_info.outputs.build_type }}.apk
            android/app/build/outputs/bundle/${{ steps.build_info.outputs.build_type }}/app-${{ steps.build_info.outputs.build_type }}.aab

  cleanup:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Delete branch
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.G_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.ref_name }}"
