export const staticPages: Array<DataType & { buildable: boolean; for: string[] }> = [
  {
    slug: 'home-creator',
    id: 'home-creator',
    canonicalSlug: 'home',
    title: 'Home Page for creator website',
    description: 'first page for creator website',
    canonical: '/',
    buildable: false,
    for: ['creator', 'hoster'],
  },
  {
    slug: 'login',
    id: 'login',
    title: 'Login',
    description: 'Login page',
    canonical: '/login',
    buildable: true,
    for: [],
  },
  {
    slug: 'signup',
    id: 'signup',
    title: 'Sign Up',
    description: 'Create a new account on our platform.',
    canonical: '/signup',
    buildable: true,
    for: [],
  },

  {
    slug: 'blog-post-details',
    id: 'blog-post-details',
    title: 'Blog Post Detail Page',
    description: 'page where blog post details will be displayed',
    canonical: '/blog-post-details',
    buildable: true,
    for: ['creator', 'blog', 'post'],
  },
  {
    slug: 'product-details',
    id: 'product-details',
    title: 'Product Detail Page',
    description: 'page where product details will be displayed',
    canonical: '/product-details',
    buildable: true,
    for: ['creator', 'store', 'ecommerce'],
  },

  {
    slug: 'pricing',
    id: 'pricing',
    title: 'Pricing',
    description: 'Explore our pricing plans and packages.',
    canonical: '/pricing',
    buildable: true,
    for: [],
  },
  {
    slug: 'app-page',
    id: 'app-page',
    title: 'App Page',
    description: 'Explore our app page.',
    canonical: '/app-download',
    buildable: true,
    for: ['creator', 'hoster'],
  },
  {
    slug: 'purchased-view',
    id: 'purchased-view',
    title: 'Puchased View',
    description: 'This is page for users after product purchase',
    canonical: '/app-download',
    buildable: true,
    for: ['creator', 'hoster'],
  },
];
