export const height = [
  {
    all: [
      "h-0",
      "h-1",
      "h-2",
      "h-3",
      "h-4",
      "h-5",
      "h-6",
      "h-8",
      "h-10",
      "h-12",
      "h-16",
      "h-20",
      "h-24",
      "h-32",
      "h-40",
      "h-48",
      "h-56",
      "h-64",
      "h-72",
      "h-80",
      "h-96",
      "h-full",
      "h-screen",
      "h-auto",
      "h-min",
      "h-max",
      "h-fit",
      "h-1/2",
      "h-1/3",
      "h-2/3",
      "h-1/4",
      "h-3/4",
      "h-1/5",
      "h-2/5",
      "h-3/5",
      "h-4/5",
      "h-1/6",
      "h-5/6",
    ],
  },
];

export const objectHeights = [
  // Base heights
  { value: 0, class: "h-0", title: "height 0" },
  { value: 1, class: "h-1", title: "height 1" },
  { value: 2, class: "h-2", title: "height 2" },
  { value: 3, class: "h-3", title: "height 3" },
  { value: 4, class: "h-4", title: "height 4" },
  { value: 5, class: "h-5", title: "height 5" },
  { value: 6, class: "h-6", title: "height 6" },
  { value: 8, class: "h-8", title: "height 8" },
  { value: 10, class: "h-10", title: "height 10" },
  { value: 12, class: "h-12", title: "height 12" },
  { value: 16, class: "h-16", title: "height 16" },
  { value: 20, class: "h-20", title: "height 20" },
  { value: 24, class: "h-24", title: "height 24" },
  { value: 32, class: "h-32", title: "height 32" },
  { value: 40, class: "h-40", title: "height 40" },
  { value: 48, class: "h-48", title: "height 48" },
  { value: 56, class: "h-56", title: "height 56" },
  { value: 64, class: "h-64", title: "height 64" },
  { value: 72, class: "h-72", title: "height 72" },
  { value: 80, class: "h-80", title: "height 80" },
  { value: 96, class: "h-96", title: "height 96" },
  { value: "full", class: "h-full", title: "full height" },
  { value: "screen", class: "h-screen", title: "screen height" },
  { value: "auto", class: "h-auto", title: "auto height" },
  { value: "min", class: "h-min", title: "min height" },
  { value: "max", class: "h-max", title: "max height" },
  { value: "fit", class: "h-fit", title: "fit height" },
  { value: "50%", class: "h-1/2", title: "height 50%" },
  { value: "33.33%", class: "h-1/3", title: "height 33.33%" },
  { value: "66.67%", class: "h-2/3", title: "height 66.67%" },
  { value: "25%", class: "h-1/4", title: "height 25%" },
  { value: "75%", class: "h-3/4", title: "height 75%" },
  { value: "20%", class: "h-1/5", title: "height 20%" },
  { value: "40%", class: "h-2/5", title: "height 40%" },
  { value: "60%", class: "h-3/5", title: "height 60%" },
  { value: "80%", class: "h-4/5", title: "height 80%" },
  { value: "16.67%", class: "h-1/6", title: "height 16.67%" },
  { value: "83.33%", class: "h-5/6", title: "height 83.33%" },

  { value: "min-h-full", class: "min-h-screen", title: "min full height" },
  { value: "max-h-full", class: "max-h-screen", title: "max full height" },

  // Large screen (sm:) heights
  { value: 0, class: "sm:h-0", title: "height 0 for Large Screen" },
  { value: 1, class: "sm:h-1", title: "height 1 for Large Screen" },
  { value: 2, class: "sm:h-2", title: "height 2 for Large Screen" },
  { value: 3, class: "sm:h-3", title: "height 3 for Large Screen" },
  { value: 4, class: "sm:h-4", title: "height 4 for Large Screen" },
  { value: 5, class: "sm:h-5", title: "height 5 for Large Screen" },
  { value: 6, class: "sm:h-6", title: "height 6 for Large Screen" },
  { value: 8, class: "sm:h-8", title: "height 8 for Large Screen" },
  { value: 10, class: "sm:h-10", title: "height 10 for Large Screen" },
  { value: 12, class: "sm:h-12", title: "height 12 for Large Screen" },
  { value: 16, class: "sm:h-16", title: "height 16 for Large Screen" },
  { value: 20, class: "sm:h-20", title: "height 20 for Large Screen" },
  { value: 24, class: "sm:h-24", title: "height 24 for Large Screen" },
  { value: 32, class: "sm:h-32", title: "height 32 for Large Screen" },
  { value: 40, class: "sm:h-40", title: "height 40 for Large Screen" },
  { value: 48, class: "sm:h-48", title: "height 48 for Large Screen" },
  { value: 56, class: "sm:h-56", title: "height 56 for Large Screen" },
  { value: 64, class: "sm:h-64", title: "height 64 for Large Screen" },
  { value: 72, class: "sm:h-72", title: "height 72 for Large Screen" },
  { value: 80, class: "sm:h-80", title: "height 80 for Large Screen" },
  { value: 96, class: "sm:h-96", title: "height 96 for Large Screen" },
  { value: "full", class: "sm:h-full", title: "full height for Large Screen" },
  { value: "screen", class: "sm:h-screen", title: "screen height for Large Screen" },
  { value: "auto", class: "sm:h-auto", title: "auto height for Large Screen" },
  { value: "min", class: "sm:h-min", title: "min height for Large Screen" },
  { value: "max", class: "sm:h-max", title: "max height for Large Screen" },
  { value: "fit", class: "sm:h-fit", title: "fit height for Large Screen" },
  { value: "50%", class: "sm:h-1/2", title: "height 50% for Large Screen" },
  { value: "33.33%", class: "sm:h-1/3", title: "height 33.33% for Large Screen" },
  { value: "66.67%", class: "sm:h-2/3", title: "height 66.67% for Large Screen" },
  { value: "25%", class: "sm:h-1/4", title: "height 25% for Large Screen" },
  { value: "75%", class: "sm:h-3/4", title: "height 75% for Large Screen" },
  { value: "20%", class: "sm:h-1/5", title: "height 20% for Large Screen" },
  { value: "40%", class: "sm:h-2/5", title: "height 40% for Large Screen" },
  { value: "60%", class: "sm:h-3/5", title: "height 60% for Large Screen" },
  { value: "80%", class: "sm:h-4/5", title: "height 80% for Large Screen" },
  { value: "16.67%", class: "sm:h-1/6", title: "height 16.67% for Large Screen" },
  { value: "83.33%", class: "sm:h-5/6", title: "height 83.33% for Large Screen" },
  { value: "min-h-full", class: "sm:min-h-screen", title: "min full height for Large Screen" },
  { value: "max-h-full", class: "sm:max-h-screen", title: "max full height for Large Screen" },
];
